version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
      - client

  server:
    build: .
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run server

  client:
    build: .
    expose:
      - "5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    environment:
      - VITE_WS_URL=wss://ws.sheckout.com
