version: '3.8'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run server

  client:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    environment:
      - VITE_WS_URL=ws://localhost:3000
